### ISSUE TITLE
Log2 gives wrong answers 

### ISSUE THREAD

**Issue by charleschege** [codemessiah/rsc#7]
If I do log2(18000) it results in 5418.54 instead of 14.13 like rustlang f32::log2() or a scientific calculator

**Comment by codemessiah** [comment]
Thanks for reporting this. I'll take a look as soon as I can. I might not be able to get a solution pushed until after Sunday, because I'm not at a computer. I'll see what I can do anyways, because I care about RSC working.

Luke

**Comment by codemessiah** [comment]
Question: which version of RSC are you using? You may want to try using the GitHub origin branch instead of a released version. I'm not sure if the latest version matches the current origin.

**Comment by codemessiah** [comment]
Nevermind. Seems the issue is there is no function called `log2` -- there's only `log`. You can [add a function for the computer in your program using the .functions field.](https://github.com/codemessiah/rsc/blob/master/src/computer.rs#L88)

The fact RSC didn't catch you is just a fault in the lexer. RSC isn't programmed to find numbers in function names, so it just read it as `log` ( `2` ) * `18000`.

**Because this issue is in the lexer, you cannot call your custom function `log2` because the same issue would happen.** I need to fix the lexer Sunday. For now, you can call it `logtwo` or something. I am sorry :(
